# General Site Info
name: Carie Phon
job: Interaction Designer
other-job: Front-End Developer
email: hello@cariephon.com

# Menu 
menu:
- {name: Skills, url: '#skills'}
- {name: Work, url: '#work'}
- {name: About, url: '#about'}
- {name: Resume, url: '#resume'}
#- {name: Notes, url: '#notes'}
- {name: Contact, url: '#contact'}

# Work
projects:
- {name: Snack Street, class: tile1 medium-tile, folder: 'snack-street', file: 'work/snack-street.html', description: Hybrid Mobile App}
- {name: Waffle, class: tile2 medium-tile, folder: 'waffle-app', file: 'work/waffle-app.html', description: Concept iPad App}
- {name: Meditation, class: tile3 small-tile, folder: 'meditation', file: 'work/meditation.html', description: jQuery Mobile App}
- {name: PFD Sale, class: tile4 small-tile, folder: 'pfd-sale', file: 'work/pfd-sale.html', description: Responsive Sale Page }
- {name: Templates, class: tile5 small-tile, folder: 'cdk-templates', file: 'work/cdk-templates.html', description: Optimized Workflow}


# About Me
bio: |	
 I'm a designer and developer with a passion for interaction design. In 2015, I graduated with a Masters in Web Design and New Media at the [Academy of Art University](http://www.academyart.edu/academics/web_design/graduate).
 
 My experience ranges from web and print design to user interface and front-end development. I’m always advocating for the user: balancing aesthetics with technology and delight with usability.
 
 When I’m not desiging or coding, you’ll find me exploring new places to eat, watching MasterChef, sketching, and playing with my dog Tofu.


skills:
- {name: HTML5, value: '4'}
- {name: CSS, value: '4'}
- {name: PHOTOSHOP, value: '4'}
- {name: ILLUSTRATOR, value: '4'}
- {name: SASS, value: '3'}
- {name: JQUERY, value: '2'}
- {name: ANGULAR, value: '2'}
- {name: JAVASCRIPT, value: '2'}


# Resume
